spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=appdb;encrypt=false
    username: sa
    password: PassW0rd

mybatis:
  config-location: classpath:/mybatis-config.xml
  type-aliases-package: com.web.memo.dao.entity
  type-handlers-package: com.web.memo.dao.typehandler
