spring:
  datasource:
    url: jdbc:mysql://root@localhost:3306/appdb
    username: root
    password: PassW0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:/mybatis-config.xml
  type-aliases-package: com.web.memo.dao.entity
  type-handlers-package: com.web.memo.dao.typehandler
